### ISSUE TITLE
Release library build contains demo images

### ISSUE THREAD

**Issue by molexx** [lopei/collageview#3]
https://jitpack.io/com/github/lopei/collageview/0.1.2/collageview-0.1.2.aar

contains res/drawable/res_item_1.jpg, res_item_2.jpg and so on which are the Simpsons etc. images shown in the demo

**Comment by metalurgus** [comment]
@molexx makes sense, but it's just a way that jitpack builds AARs - it builds entire repository, including the library, the sample app, and all the resources. A solution might be to move sample app to another repository. i'll ask @lopei

**Comment by lopei** [comment]
@molexx @metalurgus removed extra files in 0.1.3. Issue shall be closed now.

**Comment by molexx** [comment]
hmm, files still seem to be in https://jitpack.io/com/github/lopei/collageview/0.1.3/collageview-0.1.3.aar

**Comment by lopei** [comment]
@molexx yes, sorry, my fault. Will fix within a couple of hours.
