### ISSUE TITLE
How to achieve image collage view with intelligent scaling without cropping, as in Google Keep

### ISSUE THREAD

**Issue by yccheok** [lopei/collageview#4]
Thank you for creating this wonderful library.

I pretty like the image collage view as in Google Keep.

[![enter image description here][1]][1]

I try with the following code

        CollageView collageView = (CollageView) findViewById(R.id.collageView);

        collageView
            .photoMargin(1)
            .photoPadding(3)
            .backgroundColor(Color.RED)
            .photoFrameColor(Color.BLUE)
            .useFirstAsHeader(false)
            .defaultPhotosForLine(3)
            .useCards(true)
            .loadPhotos(new int[] {R.drawable.one, R.drawable.three, R.drawable.two, R.drawable.zero});

The best I can achieve is

[![enter image description here][2]][2]

If you pay attention carefully. There's one significant different. In Google Keep, it is able to scale the image more intelligently, so that there's no image cropping. All image information can be seen from the thumbnail. No information is lost.

I was wondering, do you have any idea, how can I achieve the same effect as in Google Keep?

Than you.

  [1]: https://i.stack.imgur.com/8fL0m.jpg
  [2]: https://i.stack.imgur.com/UB5Cg.jpg

**Comment by lopei** [comment]
Hey! Thank you for your message.
For now it supports only square and half height shapes, to make it "smart
shape" we'll need to do some extra coding

вс, 29 апр. 2018 г., 21:43 Yan Cheng Cheok <notifications@github.com>:

**Comment by lopei** [comment]
Not an issue. 
This is rather a suggestion for the future development.

**Comment by yccheok** [comment]
Hi, I had read the code of `collageview` and tried out.

I think the key of the solution is to apply correct `layout_weight` on the `ImageView`.

Take the following example

```
Image0 = 1280 x 720
Image1 = 685 x 963
Image2 = 1280 x 856

layout_weight for image 0 = 1 (since its height is the lowest)

layout_weight for image 1 = height0/height1 * width1/width0
                          = 720/963 * 685/1280 = 0.4001168224
                          
layout_weight for image 2 = height0/height2 * width2/width0
                          = 720/856 * 1280/1280 = 0.8411214953
```

So, using the following XML

```
    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
        
        <ImageView
            android:layout_width="0dp"
            android:width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:src="@drawable/three"
            android:adjustViewBounds="true" />

        <ImageView
            android:layout_width="0dp"
            android:width="0dp"
            android:layout_weight="0.4001168224"
            android:layout_height="wrap_content"
            android:src="@drawable/two"
            android:adjustViewBounds="true"/>

        <ImageView
            android:layout_width="0dp"
            android:width="0dp"
            android:layout_weight="0.8411214953"
            android:layout_height="wrap_content"
            android:src="@drawable/one"
            android:adjustViewBounds="true"/>
    </LinearLayout>
```

It looks like this

<img width="300" alt="0" src="https://user-images.githubusercontent.com/308276/39414952-13fdd27a-4c70-11e8-856d-5d5b1ac456af.png">

This is how it looks like, without applying `layout_weight`.

<img width="311" alt="1" src="https://user-images.githubusercontent.com/308276/39414962-30022232-4c70-11e8-8b84-f23c549deb1c.png">

**Comment by lopei** [comment]
Hi! Thanks, I will check this up and add a new "smart shape" type

пн, 30 апр. 2018 г., 7:15 Yan Cheng Cheok <notifications@github.com>:
